apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb
spec:
  replicas: 1
  selector:
    app: httpd
  template:
    metadata:
      name: mywebserver
      labels:
        app: httpd
    spec:
      containers:
      - name: mywebserver
        image: vimal13/apache-webserver-php
